name: Terraform Azure Deployment

on:
  push:
    branches:
     - feature-vm

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: parent_module

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
